name: Push new release to PyPI

on:
  release:
    types: [published]

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest

    steps:
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}